from django.contrib import admin
from .models import (Customer,
                     Product,
                     ProductView,
                     Rating,
                     Order,
                     Favorit,
                     Category,
                     CartProduct,
                     Brand,
                     TrendingProduct,
                     Slider,
                     Review,
                     Cart)

admin.site.register([Customer,
                     Product,
                     ProductView,
                     Rating,
                     Brand,
                     TrendingProduct,
                     Slider,
                     Order,
                     Favorit,
                     Category,
                     CartProduct,
                     Review,
                     Cart])
