# Generated by Django 3.1.6 on 2021-02-20 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_customer_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='image',
        ),
    ]
