# Generated by Django 3.1.6 on 2021-02-22 08:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_remove_productview_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productview',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shop.product'),
        ),
    ]
